name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jeanlescure/react-deploy-to-s3-action@main
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          NODE_ENV: production
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: build
          CLOUDFRONT_DISTRIBUTION_ID: E1WMAFPJJ21TIH
          REACT_APP_C_LEVEL_KEY: ${{ secrets.REACT_APP_C_LEVEL_KEY }}
          REACT_APP_C_LEVEL_ENDPOINT: ${{ secrets.REACT_APP_C_LEVEL_ENDPOINT }}
          REACT_APP_GOOGLE_MAPS_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_KEY }}
